name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Verify package-lock.json exists
      run: |
        if [ ! -f package-lock.json ]; then
          echo "Error: package-lock.json is missing. Please commit it to the repository."
          exit 1
        fi
    - run: npm ci
    - run: npm run build